# Generated by Django 5.2.9 on 2025-12-20 22:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_lineups', models.IntegerField(default=0)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_won', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_rate', models.FloatField(default=0, help_text='% of lineups that cashed')),
                ('top_10_rate', models.FloatField(default=0, help_text='% in top 10%')),
                ('top_1_rate', models.FloatField(default=0, help_text='% in top 1%')),
                ('avg_rank', models.FloatField(blank=True, null=True)),
                ('avg_percentile', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Strategy performances',
                'ordering': ['-total_won'],
            },
        ),
        migrations.CreateModel(
            name='NbaSlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('site', models.CharField(choices=[('FD', 'FanDuel'), ('DK', 'DraftKings')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, help_text="e.g., 'Main', 'Early', 'Late'", max_length=100)),
                ('game_count', models.IntegerField(default=0, help_text='Number of games in slate')),
                ('total_contests', models.IntegerField(default=0)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_complete', models.BooleanField(default=False, help_text='All contests graded')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'site'],
                'indexes': [models.Index(fields=['-date', 'site'], name='nba_nbaslat_date_3e5bec_idx'), models.Index(fields=['is_complete'], name='nba_nbaslat_is_comp_170f48_idx')],
                'unique_together': {('date', 'site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NbaContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest_name', models.CharField(db_index=True, max_length=200)),
                ('contest_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_entries', models.IntegerField(default=0, help_text='Total entries in contest')),
                ('prize_pool', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contest_type', models.CharField(choices=[('GPP', 'GPP - Tournament'), ('CASH', 'Cash Game'), ('50/50', '50/50'), ('DOUBLE_UP', 'Double Up'), ('H2H', 'Head to Head'), ('MULTIPLIER', 'Multiplier'), ('SATELLITE', 'Satellite')], db_index=True, default='GPP', max_length=20)),
                ('payout_places', models.IntegerField(blank=True, help_text='Number of places paid', null=True)),
                ('min_cash_line', models.IntegerField(blank=True, help_text='Rank needed to cash', null=True)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='nba.nbaslate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('features_used', models.JSONField(default=list, help_text="List of features: ['salary', 'proj_points', 'value', 'team', 'position']")),
                ('weights', models.JSONField(default=dict, help_text="Feature weights: {'salary': 0.3, 'value': 0.5, ...}")),
                ('mean_absolute_error', models.FloatField(blank=True, null=True)),
                ('root_mean_squared_error', models.FloatField(blank=True, null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_models', to='nba.nbaslate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1_id', models.CharField(db_index=True, max_length=50)),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_id', models.CharField(db_index=True, max_length=50)),
                ('player2_name', models.CharField(max_length=100)),
                ('correlation_coefficient', models.FloatField(help_text='Pearson correlation (-1 to 1)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('games_together', models.IntegerField(default=0)),
                ('same_team', models.BooleanField(default=False)),
                ('position_group', models.CharField(blank=True, help_text="e.g., 'Guards', 'Frontcourt', 'All'", max_length=50)),
                ('avg_combined_points', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-correlation_coefficient'],
                'indexes': [models.Index(fields=['-correlation_coefficient'], name='nba_playerc_correla_e37cb3_idx'), models.Index(fields=['same_team'], name='nba_playerc_same_te_94b647_idx')],
                'unique_together': {('player1_id', 'player2_id')},
            },
        ),
        migrations.CreateModel(
            name='NbaLineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('lineup_data', models.JSONField(default=dict, help_text='Full lineup with player IDs, names, positions, salaries')),
                ('projected_points', models.FloatField(blank=True, null=True)),
                ('projected_ownership', models.FloatField(blank=True, help_text='Avg ownership %', null=True)),
                ('actual_points', models.FloatField(blank=True, db_index=True, null=True)),
                ('avg_ownership', models.FloatField(blank=True, help_text='Actual avg ownership', null=True)),
                ('unique_percentage', models.FloatField(blank=True, help_text='How unique was this lineup (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('percentile', models.FloatField(blank=True, help_text='Percentile finish (0-100, lower is better)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cashed', models.BooleanField(db_index=True, default=False)),
                ('top_1_percent', models.BooleanField(default=False)),
                ('top_5_percent', models.BooleanField(default=False)),
                ('top_10_percent', models.BooleanField(db_index=True, default=False)),
                ('construction_strategy', models.CharField(blank=True, help_text="e.g., 'Balanced', 'Stars and Scrubs', 'Contrarian'", max_length=50)),
                ('stack_type', models.CharField(blank=True, help_text="e.g., 'None', '2-man stack', 'Game stack'", max_length=50)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='nba.nbacontest')),
            ],
            options={
                'ordering': ['final_rank'],
                'indexes': [models.Index(fields=['contest', 'final_rank'], name='nba_nbaline_contest_e72d0d_idx'), models.Index(fields=['cashed', 'top_10_percent'], name='nba_nbaline_cashed_d7c613_idx'), models.Index(fields=['-actual_points'], name='nba_nbaline_actual__a7d30d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NbaPlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dfs_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('team', models.CharField(db_index=True, max_length=10)),
                ('opponent', models.CharField(blank=True, max_length=10)),
                ('game_location', models.CharField(blank=True, choices=[('HOME', 'Home'), ('AWAY', 'Away')], max_length=10)),
                ('minutes_played', models.FloatField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('projected_ownership', models.FloatField(blank=True, null=True)),
                ('actual_ownership', models.FloatField(blank=True, null=True)),
                ('projected_points', models.FloatField(db_index=True)),
                ('actual_points', models.FloatField(blank=True, db_index=True, null=True)),
                ('value_projected', models.FloatField(blank=True, help_text='Projected points per $1000', null=True)),
                ('value_actual', models.FloatField(blank=True, help_text='Actual points per $1000', null=True)),
                ('game_stats', models.JSONField(blank=True, default=dict, help_text='Points, rebounds, assists, etc.')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='nba.nbaslate')),
            ],
            options={
                'ordering': ['-actual_points'],
                'indexes': [models.Index(fields=['slate', 'team'], name='nba_nbaplay_slate_i_7512b7_idx'), models.Index(fields=['-actual_points'], name='nba_nbaplay_actual__6429d4_idx'), models.Index(fields=['salary'], name='nba_nbaplay_salary_10d946_idx')],
                'unique_together': {('slate', 'dfs_id')},
            },
        ),
        migrations.AddIndex(
            model_name='nbacontest',
            index=models.Index(fields=['slate', 'contest_type'], name='nba_nbacont_slate_i_971997_idx'),
        ),
        migrations.AddIndex(
            model_name='nbacontest',
            index=models.Index(fields=['is_complete'], name='nba_nbacont_is_comp_2533c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershipmodel',
            index=models.Index(fields=['slate', 'model_version'], name='nba_ownersh_slate_i_fb78ca_idx'),
        ),
    ]
